ARTIFACTS_ROOT_DIR: artifacts

DATA_INGESTION:
  DATA_INGESTION_DIR_PATH: artifacts/<model_name>/data_ingestion
  DATA_DOWNLOAD_STORE_DIR_PATH: artifacts/<model_name>/data_ingestion/SIBI_dataset
  DATA_DOWNLOAD_STORE_TRAIN_DIR_PATH: artifacts/<model_name>/data_ingestion/SIBI_dataset/Train
  DATA_DOWNLOAD_STORE_TEST_DIR_PATH: artifacts/<model_name>/data_ingestion/SIBI_dataset/Test
  ZIP_FILE_PATH: artifacts/<model_name>/data_ingestion/SIBI_dataset/SIBI_datasets.zip
  DATA_DOWNLOAD_URL: https://huggingface.co/datasets/Anggads01/SIBI-datasets/resolve/main/SIBI_datasets.zip

DATA_PREPROCESSING:
  OBJECTS_DIR_PATH: artifacts/<model_name>/data_preprocessing/objects
  LABELS_LIST_FILE_PATH: artifacts/<model_name>/data_preprocessing/objects/label_list.pkl
  CLASS_WEIGHTS_FILE_PATH: artifacts/<model_name>/data_preprocessing/objects/class_weights.pkl
  IMAGE_EXTENSION_REGEX: "\\.(jpe?g|png)$"