MODEL_NAME: DenseNet121

DATASET_NAME: SIBI_datasets
SPLIT_RATIO: [0.9, 0.1]
LABEL_LIST: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

SEED: 42
BATCH_SIZE: 16
EPOCHS: 5
LEARNING_RATE: 0.001
CRITERION: CrossEntropyLoss
OPTIMIZER: Adam

# ====== Data Augmentation ======
IMAGE_SIZE: [224, 224, 3]
MEAN : [0., 0., 0.]
STD: [1., 1., 1.]
BRIGHTNESS: [0.9, 1.1] 
CONTRAST: [0.9, 1.1]   
SATURATION: [0.9, 1.1]  
HUE: [-0.05, 0.05]      
PROB: 0.5             

# ====== Reports ======
NORMALIZE_CONFUSION_MATRIX: True
FIGSIZE: [18, 12]